packages:
  - "apps/*"
  - "packages/*"
overrides:
  uuid: 9.0.1
allowBuilds:
  '@stellar/stellar-sdk': false
  bigint-buffer: false
  blake-hash: false
  bufferutil: false
  protobufjs: false
  tiny-secp256k1: false
  unrs-resolver: false
  usb: false
  utf-8-validate: false
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.3'
  - '@turbo/darwin-arm64@2.11.3'
  - '@turbo/linux-64@2.11.3'
  - '@turbo/linux-arm64@2.11.3'
  - '@turbo/windows-64@2.11.3'
  - '@turbo/windows-arm64@2.11.3'
  - turbo@2.11.3
